# Add a list of your extensions here (Don't forget the dot)
extensions_to_find:
  - '.jpg'
  - '.png'
  - '.gif'
  - '.bmp'
  
path_to_scan: 'M:\Pictures'
path_to_copy_to: 'M:\Pictures_test'

testing: true
# Possible values are debug, info, warning, error, critical
log_level: 'debug'